<a href="https://colab.research.google.com/github/Sol-Zito/DataScience/blob/main/Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
#Importar numpy
import numpy as np

In [11]:
#Crear un arreglo de ceros de longitud 12
arr = np.zeros(12)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
#Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
arr1 = np.zeros(10)
arr1[4] = 10
print(arr1)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [4]:
# Crear un arreglo que tenga los números del 10 al 49
arr2 = np.arange(10,50)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
arr3 = np.arange(9).reshape(3,3)
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
arrCien = np.random.random(100)
print("Media: ",np.mean(arrCien))
print("Varianza: ",np.var(arrCien))

Media:  0.5413772400584415
Varianza:  0.07800588169367702


In [20]:
#Calcular la media de un arreglo usando np.sum
media = np.sum(arrCien) / np.size(arrCien)
print(media)

0.5413772400584415


In [21]:
#Calcular la varianza de un arreglo usando np.sum y np.mean
media = np.mean(arrCien)
cuadrados = np.sum((arrCien - media)**2 )
varianza = cuadrados / (len(arrCien))

print(varianza)

0.07800588169367702
0.07800588169367702


In [9]:
#Crear un array de números aleatorios usando np.random.randn.
arrTres = np.random.randn(3)
arrTres

array([ 1.56919388,  0.18451113, -0.68920722])